# Generated by Django 3.1.5 on 2021-01-29 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0003_auto_20210129_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loans',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='offers',
            name='investor',
        ),
        migrations.RemoveField(
            model_name='offers',
            name='loan',
        ),
    ]
