# Generated by Django 3.1.5 on 2021-01-29 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0006_auto_20210129_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loans',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='offers',
            name='investor',
        ),
        migrations.RemoveField(
            model_name='offers',
            name='loan',
        ),
        migrations.AddField(
            model_name='account',
            name='investor',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='investor', to='MAIN.offers'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='owner',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='MAIN.loans'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loans',
            name='loan',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='loan', to='MAIN.offers'),
            preserve_default=False,
        ),
    ]
