# Generated by Django 3.1.5 on 2021-01-29 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0007_auto_20210129_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='investor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investor', to='MAIN.offers'),
        ),
        migrations.AlterField(
            model_name='account',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='MAIN.loans'),
        ),
        migrations.AlterField(
            model_name='loans',
            name='loan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan', to='MAIN.offers'),
        ),
    ]
