# Generated by Django 3.1.5 on 2021-01-29 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0008_auto_20210129_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='investor',
        ),
        migrations.RemoveField(
            model_name='account',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='loans',
            name='loan',
        ),
        migrations.AddField(
            model_name='loans',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='MAIN.account'),
        ),
        migrations.AddField(
            model_name='offers',
            name='investor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investor', to='MAIN.account'),
        ),
        migrations.AddField(
            model_name='offers',
            name='loan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan', to='MAIN.loans'),
        ),
    ]
